name: CrystalCavernsLobby
author: japicraft
version: '${project.version}'
main: cc.crystalcavernslobby.CrystalCavernsLobby
api-version: 1.19
depend: [PlaceholderAPI,Vault,CommandPanels,ProtocolLib,LuckPerms]
commands:
  claim:
    description: Used to claim a special voucher code.
  profile:
    description: Shows a given player's profile.
  credits:
    description: Displays all the awesome people who worked on the Crystal Caverns project.
  homes:
    description: Opens the Homes menu.
  treasury:
    description: Opens the your Treasury.
  battlepass:
    description: Opens the Battle Pass menu.
  switchserver:
    description: Used by other plugins to send players across realms.
    permission: crystalcaverns.switchserver
  crystalcaverns:
    description: Reloads the Crystal Caverns plugin's config.
    permission: crystalcaverns.reload