name: CrystalCavernsLobby
author: 'japicraft'
version: '1.0'
main: cc.crystalcavernslobby.CrystalCavernsLobby
api-version: '1.20'
depend: [PlaceholderAPI,Vault,CommandPanels,ProtocolLib,LuckPerms,UltimateAdvancementAPI]
commands:
  claim:
    description: Used to claim a special voucher code.
  profile:
    description: Shows a given player's profile.
  credits:
    description: Displays all the awesome people who worked on the Crystal Caverns project.
  homes:
    description: Opens the Homes menu.
    aliases: [waypoints, landmarks]
  crystalpass:
    description: Opens the Crystal Pass menu.
  menu:
    description: Opens the Crystal Caverns main menu.
  store:
    description: Gives a link to the Crystal Caverns store.
  spawn:
    description: Teleports the player to the server's global spawn point.
    aliases: [lobby, hub]
  purchase:
    description: Used for internal processes.
    permission: crystalcaverns.command.purchase
  reward:
    description: Used for internal processes.
    permission: crystalcaverns.command.reward
  points:
    description: Used for internal processes.
    permission: crystalcaverns.command.points
  crystalcaverns:
    description: Used for internal processes.
    aliases: [cc]
    permission: crystalcaverns.command.main